import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Montserrat, Work_Sans } from "next/font/google";
import { Toaster } from "sonner";
import RootProvider from "@/components/providers/RootProvider";

const montserrat = Montserrat({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

const worksans = Work_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-worksans",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased" suppressHydrationWarning>
          <div className={`${montserrat.variable} ${worksans.variable}`}>
            <RootProvider>{children}</RootProvider>
            <Toaster theme="dark" position="bottom-right" richColors closeButton />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
